version: '3'
services:
    generator:
        container_name: generator
        build: ./generator
        ports:
            - 8080:8080
        networks:
            - my-network
    multiplier:
        container_name: multiplier
        build: ./multiplier
        ports:
            - 8081:8081
        networks:
            - my-network
    show:
        container_name: show
        build: ./show
        ports:
            - 8082:8082
        networks:
            - my-network
networks:
    my-network:
        driver: bridge
